spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/spring
  username: postgres
  password: root
  
 jpa:
  properties:
    hibernate:
     show_sql: true
     format_sql: true
      
 